version: '3.8'

services:
  portefeuillefinancier:
    image: imenrais/portefeuillefinancier:0.0.1
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pf?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Chandler220994@
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Chandler220994@
      MYSQL_DATABASE: pf
    ports:
      - "3307:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
